server:
  port: 80

spring:
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false
  data:
    redis:
      repositories:
        enabled: false
      host: 127.0.0.1
      port: 6400
      password: kbank
    datasource:
      url: jdbc:postgresql://postgres:5432/mydatabase
      username: myuser
      password: mypassword
      driverClassName: org.postgresql.Driver
    jpa:
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      generate-ddl: true
      show-sql: true
      hibernate:
          ddl-auto: update