server:
  port: 80

spring:
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false
  freemarker:
    cache: false
    suffix: .ftl
    domain: "http://localhost:80"
  data:
    redis:
      repositories:
        enabled: false
      host: 127.0.0.1
      port: 6400
      password: kbank
  datasource:
    url: jdbc:postgresql://localhost:5432/mydatabase
    username: myuser
    password: mypassword
    driver-class-name: org.postgresql.Driver
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true