server:
  port: 80

spring:
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  freemarker:
    cache: false
    suffix: .ftl
    domain: "http://localhost:80"
  data:
    redis:
      repositories:
        enabled: false
      host: 127.0.0.1
      port: 6400
      password: kbank
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/mydatabase
    username: myuser
    password: mypassword
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: create-drop
      format_sql: true
    properties:
      hibernate:
        #      show_sql: true
        format_sql: true
logging:
  org:
    hibernate:
      type: trace